require("config-lsp/ts-fmt-lint").setup()
require("config-lsp/lsp-css")
require("config-lsp/lsp-lua")
require("config-lsp/lsp-vim")
require("config-lsp/lsp-json")
require("config-lsp/lsp-html")
require("config-lsp/lsp-python")
require("config-lsp/lsp-tsserver")
