require "typedin.config.autopairs"
require "typedin.config.comment"
require "typedin.config.dial"
require "typedin.config.gitsigns"
require "typedin.config.hop"
require "typedin.config.null-ls"
-- require "typedin.config.nvimtree"
require "typedin.config.neotree"
require "typedin.config.treesitter"
require "typedin.config.ufo"
require "typedin.config.vim-test"
