require "typedin.config.autopairs"
require "typedin.config.comment"
require "typedin.config.gitsigns"
require "typedin.config.null-ls"
require "typedin.config.nvimtree"
require "typedin.config.treesitter"
require "typedin.config.vim-test"
